### ISSUE TITLE
When installing for NUXT just get an error screen.

### ISSUE THREAD

**Issue by joeycaughey** [vue-wordpress/nuxt#15]
I've ran through the process of installing the plugin for NUXT however just get an error screen when trying to access any routes.   The wordpress API is working and confirmed.  I've also tired both the auto and manual pages.

https://paste.pics/f8945d07f975650d46c71e23fe91c5aa

**Comment by Fifciu** [comment]
Hi @joeycaughey 
Have you added `@vue-wordpress/core` to build.transpile array in the nuxt.config.js?
I am also wondering if you created an empty Vuex module?

https://docs.vuewordpress.io/guide/getting-started/installation/#nuxt-js

If those 2 things would not help you. Please send me repository with your project and I will help you
