### ISSUE TITLE
https://nuxt.vuewordpress.io - Not Accessible

### ISSUE THREAD

**Issue by rajesh-h** [vue-wordpress/nuxt#16]
Hi,

https://nuxt.vuewordpress.io is not accessible. 
Is there any other demo page to view how things look at the end?

Thanks

**Comment by allozaur** [comment]
Hi @rajesh-h!

Currently the demo which is a Nuxt App is available here :)

https://vuewordpress.io/apple/

**Comment by rajesh-h** [comment]
@allozaur Thank you for Feedback.

I apologies for my limited knowledge on this.

Before I try this module I would like to know , is there anything to be done on the wordpress installation?  What I understood from the documentation is it is more of front end. There is no changes needs to be done on wordpress installation. Am I correct?

**Comment by allozaur** [comment]
You don’t need to install anything specific on WordPress to make it work in basic setup. 

Please find more info about installation and configuring this here — https://docs.vuewordpress.io

**Comment by rajesh-h** [comment]
Thank you, starting my journey on this lets see where I will end up :)

Meanwhile just wanted to know do you have plans to make this package able to write comments? Like users can upload comments to post, also other features like Login etc?

**Comment by allozaur** [comment]
Yeah! We do plan to implement these features in 2020

**Comment by rajesh-h** [comment]
Hi,

I am slightly confused right now. It will be helpful if you can guide me. I am sorry if I am missing something baisc. My current requirement is to get all posts from my website.

Created new wordpress website restApi here- https://cookingshooking.com/test/wp-json/wp/v2/posts/
I created new nuxt project installed @vue-wordpress/nuxt made necessary adjustment like store and transpile.

Now I created a new folder and _index.vue under pages - pages/recipes/_index.vue

added below code for getting all posts on this page.

```
<template>
  <section class="wrapper">
    <Sections v-if="wpData" :data="wpData" />
  </section>
</template>

<script>
import wpData from '@vue-wordpress/core/mixins/wpData'
import { FetchHookTypes } from '@vue-wordpress/core/types'

export default {
  name: 'MyCustomPage',
  mixins: [
    wpData(
      {
        slug: '',
        type: ''
      },
      FetchHookTypes.AsyncData
    )
  ]
}
</script>
```

Now i got below error when i went to this page:
`http://localhost:3000/recipes`

```
NuxtServerError
render function or template not defined in component: NuxtLink

```

**Comment by allozaur** [comment]
@Fifciu could you help @rajesh-h out?

**Comment by Fifciu** [comment]
Hi @rajesh-h 
I have some ideas which might help you:
- Set *type* to `posts` and slug to `hello-world` for test purposes
- You should not use Sections component anymore it will be deprecated in the next Big update
- How does look your configuration inside *nuxt.config.js*?
- Inside wpData object set **dataName** a value would be name of data object with fetched content. So if you set dataName to **someThing** then you could access data by this.someThing
- You could also try to enable spa mode instead of Universal and check content of Vuex/console there might be some helpful information

If none of that helps you, please provide me access to the repo. I will fetch it and figure out what's wrong locally.

**Comment by rajesh-h** [comment]
@Fifciu I applied each and every step, got same error on ssr mode and there was a loading circle when changed to spa. but no data in both the cases.

@allozaur Below is the repo, i have added you two as contributors on this repo.

`https://github.com/rajesh-h/cswp `

**Comment by rajesh-h** [comment]
I observed something. 
Once I enable this plugin I do not get my regular index page itself. This is the default nuxt index page.

I get below error once module is enabled. looks like issues is popped up from axios module inside vuewordpress module.

Looks like this is pooing up from the axios module which is present inside @vue-wordpress/core

![image](https://user-images.githubusercontent.com/6675921/69894154-555b0400-1324-11ea-9a33-40b4fdf861db.png)

**Comment by rajesh-h** [comment]
Also can you please confirm is this package works based on Json API of wordpress or it takes different approach?

I see you are calling this https://wp.vuewordpress.io/apple (Apple is slug here) in your apple index page

I see same structure on https://wp.vuewordpress.io/examples/apple/ just that it is not organized as the https://vuewordpress.io/apple


I hope you are getting my question.

Thanks,
Rajesh

**Comment by Fifciu** [comment]
> Also can you please confirm is this package works based on Json API of wordpress or it takes different approach?
> 
> I see you are calling this https://wp.vuewordpress.io/apple (Apple is slug here) in your apple index page
> 
> I see same structure on https://wp.vuewordpress.io/examples/apple/ just that it is not organized as the https://vuewordpress.io/apple
> 
> I hope you are getting my question.
> 
> Thanks,
> Rajesh

Yes I can confirm that. We use Wp Rest Api Json. The other essesntial thing is proper structure of permalinks. It should look like that: https://wp.vuewordpress.io/wp-json/wp/v2/pages?slug=apple

I've checked your repo and I could not fix it. I think there might be a problem with different build targets. I'll try to fix it in the new patch which should be released in the following week.

If you would like to have more direct contact with me. Join vuewordpress slack: vuewordpressworkspace.slack.com

**Comment by rajesh-h** [comment]
Thank you very much for the information. I will be in touch on slack soon.

**Comment by Fifciu** [comment]
Hi @rajesh-h what is status of your issue?

**Comment by rajesh-h** [comment]
@Fifciu I have not continued with this as of now.

I am currently planning to move away from Wordpress. I am now working on ghost blog.  I will give it some time. if that also not works then I will come back to wordpress.

Thank you very much for the followup.
